### PR TITLE
Replaced Open3 with Posix-spawn to reduce process memory leak

### PR DESCRIPTION
**Pull request by santhanakarthikeyan**
Ohloh SCM consumes huge memory when iterating through each commits of large repositories like [liferay-portal](https://github.com/liferay/liferay-portal)

The reason for huge memory consumption is due to `Open3.capture3` which internally uses ``fork()`` that increases the parent process memory for every subsequent call of ``capture3()``. To fix this problem i have replaced ``Open3`` with ruby [posix-spawn](https://github.com/rtomayko/posix-spawn) which greatly reduces the memory consumption by 10X.

### CODE REVIEW

**Comment by santhanakarthikeyan** [comment]
Sample code to prove posix-spawn will consume less memory.

```ruby
require 'open3'
require 'posix/spawn'
require 'benchmark'

pid = Process.fork do
  Benchmark.bm do |bm|
    bm.report do
      1000.times do
        out, err, status = Open3.capture3('ls -lrt')
      end
    end
  end
  out, err, status = Open3.capture3("pmap #{Process.pid} | tail -1 | awk '{print $2}'")
  puts "Open3 process memory: #{out}"
end

Process.waitpid(pid)

puts "\n\n"

pid = Process.fork do
  Benchmark.bm do |bm|
    bm.report do
      1000.times do
        out, err, status = POSIX::Spawn::Child.new('ls -lrt')
      end
    end
  end
  child = POSIX::Spawn::Child.new("pmap #{Process.pid} | tail -1 | awk '{print $2}'")
  puts "Posix-spawn process memory: #{child.out}"
end
Process.waitpid(pid)
```

**Comment by PeterDP** [comment]
This is encouraging.  Can we extrapolate to our own memory usage?  This example shows that using POSIX::Spawn will use 43,328K instead of 248,708K (17.42%).  Two questions:
1) Should we expect to seem similar reduction in executing our code (do you have any runs using ohloh_scm?)
2) Is it enough?  Even if we use only 17% of the RAM, some of these processes were dying early on in the cycle.  It may be that this only extends the amount of work before we run OOM.

**Comment by PeterDP** [comment]
Also, it looks like we need to do some maintenance on Travis CI. We need to increase the Ruby version to ruby 2.0.0p384 and we need to install the "posix/spawn" gem.

**Comment by santhanakarthikeyan** [comment]
Yes i ran in our code and below are the process memory trace with and without posix-spawn. Actually i couldn't see exponential memory growth when using posix_spawn.

**Open3**
```
Started at 2016-04-12-01:47:30
Free Memory: 61
Memory Usage of PID 19045 is 1005504K : ProcessName [S Job 42 (2/170332) Running]

Started at 2016-04-12-01:48:00
Free Memory: 41
Memory Usage of PID 19045 is 2639276K : ProcessName [S Job 42 (36/170332) Running]

Started at 2016-04-12-01:48:30
Free Memory: 28
Memory Usage of PID 19045 is 3682868K : ProcessName [S Job 42 (66/170332) Running]

Started at 2016-04-12-01:52:16
Free Memory: 6
Memory Usage of PID 19045 is 6402052K : ProcessName [S Job 42 (233/170332) Running]

Started at 2016-04-12-01:52:46
Free Memory: 6
Memory Usage of PID 19045 is 6528428K : ProcessName [S Job 42 (240/170332) Running]
```

**posix-spawn**

```
Started at 2016-04-12-01:59:32
Free Memory: 67
Memory Usage of PID 1576 is 891912K : ProcessName [S Job 42 (55/170091) Running]

Started at 2016-04-12-02:00:02
Free Memory: 67
Memory Usage of PID 1576 is 916236K : ProcessName [S Job 42 (55/170091) Running]

Started at 2016-04-12-02:00:33
Free Memory: 68
Memory Usage of PID 1576 is 896216K : ProcessName [S Job 42 (91/170091) Running]

Started at 2016-04-12-02:01:03
Free Memory: 68
Memory Usage of PID 1576 is 894468K : ProcessName [S Job 42 (158/170091) Running]

Started at 2016-04-12-02:01:33
Free Memory: 67
Memory Usage of PID 1576 is 938088K : ProcessName [S Job 42 (183/170091) Running]

Started at 2016-04-12-02:02:03
Free Memory: 65
Memory Usage of PID 1576 is 1092448K : ProcessName [S Job 42 (183/170091) Running]

Started at 2016-04-12-02:02:33
Free Memory: 65
Memory Usage of PID 1576 is 1100684K : ProcessName [S Job 42 (230/170091) Running]


```

**Comment by PeterDP** [comment]
Thanks for the data; it's very helpful.  

The assessment below was based upon the the assumption that these jobs ran on the similar sized repositories (since the total number of steps differ) and similar number steps would therefore represent a similar point in the process.  Therefore, steps 233 and 230 were selected as the end point and steps 66 and 55 were selected as the starting points because these number sets are the closest to one another

The `popen3` call increased 73.83% from step 66 (3,596.55 MB) to step 233 (6,252.00 MB).

The `posix` call increased only 20.13% from step 55 (894.76 MB) to step 230 (1,074.89 MB).

For the posix call, one observes that step 230 is just over 0.13% of the entire process. If there is a 180 MB memory growth every 250 steps, then we could estimate that this repository might use 4.5 GB.

Therefore, the next question is: What happens when we try to complete the SLOC process?

**Comment by santhanakarthikeyan** [comment]
For comparison, i re-sloc the liferay repo from step 1 so that it would be easy to track. I could able to replicate the production issue whenever i re-sloc this repo.

**Open3**

When i ``re-Sloc`` this job with ``Open3`` the memory consumption drastically increased while processing the 6th step.  The OOM killed the job when this process started consuming swap memory.

I noticed that every time i re-sloc , exactly while processing 6th step the process get killed due to Out of Memory. I was curious to know what's there in 6th step. As per our code the 6th step is nothing but job is processing 7th commit and that particular commit has more than 3000 diffs. 

```sql
openhub_development=# select commit_id, count(*) from diffs where commit_id in (SELECT commits.id FROM commits WHERE commits.code_set_id = 2 and commits.position > 0 ORDER BY commits.position limit 10) group by commit_id order by commit_id;
 commit_id | count 
-----------+-------
     46716 |    54
     46717 |     5
     46718 |     2
     46719 |   105
     46720 |    78
     46721 |  2752
     46722 |  3156
     46723 |   457
(8 rows)
```

So both 6th and 7th commit had around 6k diffs and i assume less frequent ``fork()`` call has raised the process memory due to its page tables duplication.

**Memory Traces**

```
Script started

Started at 2016-04-12-10:27:32
Total Memory: 75 :: Free Memory: 70 :: Free Swap Memory: 80

Started at 2016-04-12-10:28:32
Total Memory: 56 :: Free Memory: 33 :: Free Swap Memory: 80
Memory Usage of PID 22183 is 3435412K : ProcessName [S Job 43 (6/171597) Running]

Started at 2016-04-12-10:29:33
Total Memory: 41 :: Free Memory: 6 :: Free Swap Memory: 77
Memory Usage of PID 22183 is 5937784K : ProcessName [S Job 43 (6/171597) Running]

Started at 2016-04-12-10:30:35
Total Memory: 36 :: Free Memory: 6 :: Free Swap Memory: 67
Memory Usage of PID 22183 is 6605128K : ProcessName [S Job 43 (6/171597) Running]

Started at 2016-04-12-10:31:20
Total Memory: 36 :: Free Memory: 6 :: Free Swap Memory: 66
Memory Usage of PID 22183 is 6605128K : ProcessName [S Job 43 (6/171597) Running]

Started at 2016-04-12-10:31:35
Total Memory: 74 :: Free Memory: 79 :: Free Swap Memory: 70
```

**Comment by santhanakarthikeyan** [comment]
**Posix-Spawn**

I repeated exact same steps as above but this time i ran with ``posix-spawn``. 

Below is the process memory snapshots that i have taken at different time slots so that it would be helpful to see the memory fluctuation. We could see few memory variations and spikes due to **Garbage Collector**

In long run i believe GC will take care of cleaning unused memory and it will maintain the process memory to optimal value. As of now i noticed that it tries to maintain around 3GB. 

Observe the initial traces, within 2minutes the step 7 & 8 are completed with 1GB of memory. Later the memory increased to around 4GB at 11:13 but GC cleaned unused memory and reduced the process memory to 2.7GB at 11:15. 

```
Script started

Started at 2016-04-12-10:52:27
Total Memory: 75 :: Free Memory: 72 :: Free Swap Memory: 78

Started at 2016-04-12-10:53:28
Total Memory: 69 :: Free Memory: 61 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 1132100K : ProcessName [S Job 44 (6/171597) Running]

Started at 2016-04-12-10:54:28
Total Memory: 69 :: Free Memory: 61 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 1096820K : ProcessName [S Job 44 (7/171597) Running]
.
.
.
Started at 2016-04-12-11:04:30
Total Memory: 66 :: Free Memory: 55 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 1594572K : ProcessName [S Job 44 (1050/171597) Running]

Started at 2016-04-12-11:05:30
Total Memory: 60 :: Free Memory: 43 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 2553336K : ProcessName [S Job 44 (1191/171597) Running]

Started at 2016-04-12-11:06:31
Total Memory: 66 :: Free Memory: 55 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 2054581K : ProcessName [S Job 44 (1050/171597) Running]

.
.
.
Started at 2016-04-12-11:10:32
Total Memory: 58 :: Free Memory: 39 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 2774908K : ProcessName [S Job 44 (1689/171597) Running]

Started at 2016-04-12-11:12:32
Total Memory: 59 :: Free Memory: 41 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 2616360K : ProcessName [S Job 44 (1822/171597) Running]

Started at 2016-04-12-11:12:47
Total Memory: 55 :: Free Memory: 32 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 3334276K : ProcessName [S Job 44 (1831/171597) Running]

Started at 2016-04-12-11:13:02
Total Memory: 50 :: Free Memory: 22 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 4131524K : ProcessName [S Job 44 (1835/171597) Running]

Started at 2016-04-12-11:13:32
Total Memory: 60 :: Free Memory: 42 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 2610000K : ProcessName [S Job 44 (1836/171597) Running]

Started at 2016-04-12-11:14:02
Total Memory: 56 :: Free Memory: 35 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 3196452K : ProcessName [S Job 44 (1837/171597) Running]

Started at 2016-04-12-11:14:33
Total Memory: 59 :: Free Memory: 40 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 2796596K : ProcessName [S Job 44 (1915/171597) Running]

Started at 2016-04-12-11:15:33
Total Memory: 59 :: Free Memory: 40 :: Free Swap Memory: 78
Memory Usage of PID 29219 is 2796596K : ProcessName [S Job 44 (2002/171597) Running]
.
.
.
Started at 2016-04-12-11:29:36
Total Memory: 56 :: Free Memory: 31 :: Free Swap Memory: 82
Memory Usage of PID 29219 is 2799088K : ProcessName [S Job 44 (3105/171597) Running]
.
.
Started at 2016-04-12-11:37:24
Total Memory: 46 :: Free Memory: 10 :: Free Swap Memory: 82
Memory Usage of PID 29219 is 4536816K : ProcessName [S Job 44 (3415/171597) Running]

Started at 2016-04-12-11:37:39
Total Memory: 46 :: Free Memory: 10 :: Free Swap Memory: 82
Memory Usage of PID 29219 is 4536816K : ProcessName [S Job 44 (3415/171597) Running]
.
.
Started at 2016-04-12-11:58:14
Total Memory: 50 :: Free Memory: 19 :: Free Swap Memory: 82
Memory Usage of PID 29219 is 3514164K : ProcessName [S Job 44 (5422/171597) Running]

Started at 2016-04-12-11:58:29
Total Memory: 50 :: Free Memory: 19 :: Free Swap Memory: 82
Memory Usage of PID 29219 is 3514164K : ProcessName [S Job 44 (5446/171597) Running]
```

**Comment by santhanakarthikeyan** [comment]
I have done a load testing with posix-spawn to ensure the reliability. For load testing i took the top 5 commits which has huge diffs. Posix-spawn passed this load testing as well. 

```sql
select commit_id, count(*) from diffs where commit_id in (SELECT commits.id FROM commits WHERE commits.code_set_id = 2 and commits.position > 0 ORDER BY commits.position) group by commit_id having count(*) > 1000 order by count(*) desc limit 5;
 commit_id | count 
-----------+-------
    104173 | 57948
     84318 | 35382
     84317 | 35382
    112836 | 30444
    107440 | 26308
```

**Posix-spawn**
```
Script started

Started at 2016-04-12-12:20:41
Total Memory: 71 :: Free Memory: 60 :: Free Swap Memory: 83

Started at 2016-04-12-12:20:56
Total Memory: 69 :: Free Memory: 55 :: Free Swap Memory: 83
Memory Usage of PID 21426 is 641960K : ProcessName [S Job 45 (0/5) Running]

Started at 2016-04-12-12:21:56
Total Memory: 66 :: Free Memory: 50 :: Free Swap Memory: 83
Memory Usage of PID 21426 is 984588K : ProcessName [S Job 45 (0/5) Running]

Started at 2016-04-12-13:07:07
Total Memory: 66 :: Free Memory: 49 :: Free Swap Memory: 84
Memory Usage of PID 21426 is 1108668K : ProcessName [S Job 45 (0/5) Running]

Started at 2016-04-12-13:07:22
Total Memory: 65 :: Free Memory: 47 :: Free Swap Memory: 84
Memory Usage of PID 21426 is 1232984K : ProcessName [S Job 45 (1/5) Running]

Started at 2016-04-12-13:24:27
Total Memory: 65 :: Free Memory: 47 :: Free Swap Memory: 84
Memory Usage of PID 21426 is 1292440K : ProcessName [S Job 45 (1/5) Running]

Started at 2016-04-12-13:24:42
Total Memory: 66 :: Free Memory: 49 :: Free Swap Memory: 84
Memory Usage of PID 21426 is 1146504K : ProcessName [S Job 45 (2/5) Running]

Started at 2016-04-12-13:38:45
Total Memory: 64 :: Free Memory: 45 :: Free Swap Memory: 84
Memory Usage of PID 21426 is 1338384K : ProcessName [S Job 45 (2/5) Running]

Started at 2016-04-12-13:39:00
Total Memory: 65 :: Free Memory: 47 :: Free Swap Memory: 84
Memory Usage of PID 21426 is 1135692K : ProcessName [S Job 45 (3/5) Running]

Total Memory: 65 :: Free Memory: 46 :: Free Swap Memory: 84
Memory Usage of PID 21426 is 1176232K : ProcessName [S Job 45 (3/5) Running]

Started at 2016-04-12-13:55:19
Total Memory: 64 :: Free Memory: 45 :: Free Swap Memory: 84
Memory Usage of PID 21426 is 1273520K : ProcessName [S Job 45 (4/5) Running]

Started at 2016-04-12-14:05:52
Total Memory: 64 :: Free Memory: 45 :: Free Swap Memory: 84
Memory Usage of PID 21426 is 1251900K : ProcessName [S Job 45 (4/5) Running]

Started at 2016-04-12-14:06:07
Total Memory: 65 :: Free Memory: 47 :: Free Swap Memory: 84
Memory Usage of PID 21426 is 1111224K : ProcessName [S Job 45 (5/5) Running]

Started at 2016-04-12-14:15:24
Total Memory: 65 :: Free Memory: 46 :: Free Swap Memory: 84
Memory Usage of PID 21426 is 1197852K : ProcessName [S Job 45 (5/5) Running]
```

**Open3**

``Open3`` failed to even process first commit and crashed within 10 minutes 

```
Script started

Started at 2016-04-12-15:06:21
Total Memory: 70 :: Free Memory: 56 :: Free Swap Memory: 84

Started at 2016-04-12-15:06:36
Total Memory: 67 :: Free Memory: 50 :: Free Swap Memory: 84
Memory Usage of PID 16993 is 708048K : ProcessName [S Job 45 (0/21) Running]

Started at 2016-04-12-15:06:51
Total Memory: 63 :: Free Memory: 42 :: Free Swap Memory: 84
Memory Usage of PID 16993 is 1570360K : ProcessName [S Job 45 (0/21) Running]

Started at 2016-04-12-15:07:06
Total Memory: 61 :: Free Memory: 38 :: Free Swap Memory: 84
Memory Usage of PID 16993 is 1888888K : ProcessName [S Job 45 (0/21) Running]

Started at 2016-04-12-15:15:09
Total Memory: 61 :: Free Memory: 38 :: Free Swap Memory: 84
Memory Usage of PID 16993 is 1883468K : ProcessName [S Job 45 (0/21) Running]

Started at 2016-04-12-15:15:24
Total Memory: 59 :: Free Memory: 34 :: Free Swap Memory: 84
Memory Usage of PID 16993 is 2308340K : ProcessName [S Job 45 (0/21) Running]

Started at 2016-04-12-15:15:54
Total Memory: 49 :: Free Memory: 14 :: Free Swap Memory: 84
Memory Usage of PID 16993 is 3918400K : ProcessName [S Job 45 (0/21) Running]

Started at 2016-04-12-15:16:54
Total Memory: 40 :: Free Memory: 7 :: Free Swap Memory: 74
Memory Usage of PID 16993 is 5599848K : ProcessName [S Job 45 (0/21) Running]

Started at 2016-04-12-15:17:55
Total Memory: 35 :: Free Memory: 6 :: Free Swap Memory: 65
Memory Usage of PID 16993 is 6452152K : ProcessName [S Job 45 (0/21) Running]

Started at 2016-04-12-15:18:10
Total Memory: 74 :: Free Memory: 78 :: Free Swap Memory: 71
```

**Comment by PeterDP** [comment]
The data looks very compelling. Thank you for all this exploration.

**Pull request merged**
