### PR TITLE
OTWO-4588 Return empty svn tags if it is non-tagged repository

### PR DESCRIPTION
**Pull request by Priya5**

### CODE REVIEW

**Comment by rapbhan** [comment]
LGTM

**Comment by PDegenPortnoy** [comment]
Why was this the correction?  What was the root cause that this addresses?

**Comment by Priya5** [comment]
For svn repository which does not have tags, https://github.com/blackducksoftware/ohloh_scm/blob/9acff30b46e560ed327d1213a49ee44b12090261/lib/ohloh_scm/adapters/svn/misc.rb#L147 will return empty array.
Running `[ ][1..-1]` on it will return nil, which causes the issue. So, I have used [ ].drop(1), which will return [ ].

**Comment by PDegenPortnoy** [comment]
For posterity, the `end[1..-1]` code returns the rest of the array by skipping the first element.  However, for an empty array, this returns `nil`, which causes problems downstream.  The method needs to return an array.  Changing that line to `end.drop(1)` will return the rest of the array by dropping the first element, but will always return an array even if the array was empty to start iwth.

**Pull request merged**
