### PR TITLE
darcs support for ohloh

### PR DESCRIPTION
**Pull request by simonmichael**
This is Neil Mayhew's recent update of my three year old darcs support patches, cf https://github.com/simonmichael/ohloh_scm/pull/1 .

### CODE REVIEW

**Comment by marclaporte** [comment]
bump :-)

**Comment by neilmayhew** [comment]
@PeterDP: I'm sorry for the lack of response on this. I'm not a darcs user myself, so someone else needs to test this. I was just helping out with resolving the git conflicts.

It looks like this PR has been superseded by #23 so maybe it should be closed, especially since it now has conflicts. @simonmichael, how do you feel about that?

**Comment by simonmichael** [comment]
If so, fine with me - thanks.

**Comment by PeterDP** [comment]
Closing PR as it's been superseded by #23

**Pull request closed without merging**
