### PR TITLE
OTWO-5265 Removed String Encoder to retain the original(encoding) data

### PR DESCRIPTION
**Pull request by rapbhan**

### CODE REVIEW

**Comment by rapbhan** [comment]
retest this please

**Comment by PDegenPortnoy** [comment]
I see the tests for invalid encoding have been removed as well. Were those test just to test the `string_encoder` functionality? Is there a possibility that there will be side effects when we encounter repositories with encoding problems? Or, are we really at a point where the `string_encoder` is no longer needed?

**Comment by rapbhan** [comment]
If I am not wrong, we wanted to retain the original data "as is" and the `string_encoder` actually replace the undefined chars to the `�` which we wanted to prevent from happening.

**Comment by notalex** [comment]
What string_encoder is doing might be unexpected for end users like Fisbot. We must fix string_encoder behaviour to reflect what we need. If we allow non utf strings through ohloh_scm, it would mean other users of ohloh_scm have to deal with invalid encodings themselves. This would mark a major change in intended behaviour. In OhlohUI we use force_encoding while in OhlohScm we encode. Both do different things.

**Comment by PDegenPortnoy** [comment]
Are we dropping this PR in favor of the approach of having Ohloh SCM use `force_encoding`? If we, we still need to make sure Ohloh SCM correctly handles repositories with invalid encodings because they do exist

**Comment by rapbhan** [comment]
Closing this MR and the other MR #93 has been opened for the same issue

**Pull request closed without merging**
