### PR TITLE
OTWO-4281 Configured travis ssh setup and its dependencies

### PR DESCRIPTION
**Pull request by aruncsengr**
Configured SSH setup in Travis builds, re-factored travis config files and made version bump.

### CODE REVIEW

**Comment by notalex** [comment]
Please remove version bump from this PR. We do version bump directly on master after we merge in PRs. There are 2 PRs right now still undergoing review. Versioning is done only after we are sure of the change.

**Comment by aruncsengr** [comment]
Sure Alex, will do.

**Comment by notalex** [comment]
This PR will have merge conflicts with OTWO-4267. The uncommon change here is the `.travis_ssh_setup`. Lets close this PR, merge OTWO-4267 and create new PR against master.

**Comment by notalex** [comment]
LGTM

**Pull request merged**
