### PR TITLE
Clean modified files before switching branch

### PR DESCRIPTION
**Pull request by karthikeyanBD**

### CODE REVIEW

**Comment by notalex** [comment]
This is an old logic. Before we change it, we need to be aware of which issue this fixes. Also please tag it to a ticket.

**Comment by karthikeyanBD** [comment]
@notalex refer 5702. Linked with mariaDB failure

**Comment by notalex** [comment]
Please include the ticket number in commit message. It will help tracing back the change.

**Comment by karthikeyanBD** [comment]
@notalex Added the requested changes. Can you review again please.

**Comment by Priya5** [comment]
LGTM

**Pull request merged**
